function twentytwenty = import2020
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx
%    Worksheet: 2020+
%
% Auto-generated by MATLAB on 16-Oct-2019 12:37:45

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 35);

% Specify sheet and range
opts.Sheet = "2020+";
opts.DataRange = "A2:AI18357";

% Specify column names and types
opts.VariableNames = ["gene", "oncogenescore", "tsgscore", "otherscore", "driverscore", "oncogenepvalue", "oncogeneqvalue", "tsgpvalue", "tsgqvalue", "driverpvalue", "driverqvalue", "genelength", "silent", "nonsense", "splicesite", "missense", "recurrentmissense", "normalizedmissensepositionentropy", "frameshiftindel", "inframeindel", "normalizedmutationentropy", "MeanMissenseMGAEntropy", "MeanVESTScore", "loststartandstop", "missensetosilent", "nonsilenttosilent", "inactivatingpvalue", "entropypvalue", "vestpvalue", "combinedpvalue", "expression_CCLE", "replication_time", "HiC_compartment", "gene_betweeness", "gene_degree"];
%opts.SelectedVariableNames = ["gene", "oncogenescore", "tsgscore", "otherscore", "driverscore", "oncogenepvalue", "oncogeneqvalue", "tsgpvalue", "tsgqvalue", "driverpvalue", "driverqvalue", "genelength", "silent", "nonsense", "splicesite", "missense", "recurrentmissense", "normalizedmissensepositionentropy", "frameshiftindel", "inframeindel", "normalizedmutationentropy", "MeanMissenseMGAEntropy", "MeanVESTScore", "loststartandstop", "missensetosilent", "nonsilenttosilent", "inactivatingpvalue", "entropypvalue", "vestpvalue", "combinedpvalue", "expression_CCLE", "replication_time", "HiC_compartment", "gene_betweeness", "gene_degree"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.SelectedVariableNames = ["gene", "driverscore"];

opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
twentytwenty = readtable("C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts