function activedriver = importActiveDriver
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx
%    Worksheet: ActiveDriver
%
% Auto-generated by MATLAB on 16-Oct-2019 12:39:43

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "ActiveDriver";
opts.DataRange = "A2:C9831";

% Specify column names and types
opts.VariableNames = ["gene", "p", "fdr"];
%opts.SelectedVariableNames = ["gene", "p", "fdr"];
opts.VariableTypes = ["string", "double", "double"];
opts.SelectedVariableNames = ["gene", "p"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
activedriver = readtable("C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts