function oncodrivefm = importOncodrivefm
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx
%    Worksheet: OncodriveFM
%
% Auto-generated by MATLAB on 16-Oct-2019 12:38:21

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "OncodriveFM";
opts.DataRange = "A2:C18468";

% Specify column names and types
opts.VariableNames = ["ID", "PVALUE", "QVALUE"];
opts.SelectedVariableNames = ["ID", "PVALUE"];
opts.VariableTypes = ["string", "double", "double"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
oncodrivefm = readtable("C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts