function oncodrivefml = importOncodrivefml
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx
%    Worksheet: OncodriveFML
%
% Auto-generated by MATLAB on 16-Oct-2019 12:39:17

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = "OncodriveFML";
opts.DataRange = "A2:I18829";

% Specify column names and types
opts.VariableNames = ["index", "muts", "muts_recurrence", "samples_mut", "pvalue", "qvalue", "pvalue_neg", "qvalue_neg", "symbol"];
%opts.SelectedVariableNames = ["index", "muts", "muts_recurrence", "samples_mut", "pvalue", "qvalue", "pvalue_neg", "qvalue_neg", "symbol"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "string"];
opts.SelectedVariableNames = ["pvalue", "symbol"];

opts = setvaropts(opts, [1, 9], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 9], "EmptyFieldRule", "auto");

% Import the data
oncodrivefml = readtable("C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts