function tuson = importTuson
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx
%    Worksheet: TUSON
%
% Auto-generated by MATLAB on 16-Oct-2019 12:37:27

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 25);

% Specify sheet and range
opts.Sheet = "TUSON";
opts.DataRange = "A3:Y19322";

% Specify column names and types
opts.VariableNames = ["Gene", "Silent", "Nonsense", "Frameshift", "LOF", "Splice", "MissenseBenign", "MissenseDamaging", "Benign", "LOFTOBenignRatio", "SpliceTOBenignRatio", "MissenseDamagingTOBenignRatio", "pvalueLOFTOBenignRatio", "pvalueSpliceTOBenignRatio", "pvalueMissenseDamagingTOBenignRatio", "qvalueLOFTOBenignRatio", "qvalueSpliceTOBenignRatio", "qvalueMissenseDamagingTOBenignRatio", "EntropyScore", "pvalueEntropy", "qvalueEntropy", "TUSONcombinedpvalueTSG", "TUSONcombinedqvalueTSG", "TUSONcombinedpvalueOG", "TUSONcombinedqvalueOG"];
%opts.SelectedVariableNames = ["Gene", "Silent", "Nonsense", "Frameshift", "LOF", "Splice", "MissenseBenign", "MissenseDamaging", "Benign", "LOFTOBenignRatio", "SpliceTOBenignRatio", "MissenseDamagingTOBenignRatio", "pvalueLOFTOBenignRatio", "pvalueSpliceTOBenignRatio", "pvalueMissenseDamagingTOBenignRatio", "qvalueLOFTOBenignRatio", "qvalueSpliceTOBenignRatio", "qvalueMissenseDamagingTOBenignRatio", "EntropyScore", "pvalueEntropy", "qvalueEntropy", "TUSONcombinedpvalueTSG", "TUSONcombinedqvalueTSG", "TUSONcombinedpvalueOG", "TUSONcombinedqvalueOG"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.SelectedVariableNames = ["Gene", "TUSONcombinedpvalueTSG", "TUSONcombinedpvalueOG"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
tuson = readtable("C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts