function mutsigcv = importMutsig
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx
%    Worksheet: MutsigCV
%
% Auto-generated by MATLAB on 16-Oct-2019 12:36:41

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 15);

% Specify sheet and range
opts.Sheet = "MutsigCV";
opts.DataRange = "A2:O18861";

% Specify column names and types
opts.VariableNames = ["gene", "expr", "reptime", "hic", "N_nonsilent", "N_silent", "N_noncoding", "n_nonsilent", "n_silent", "n_noncoding", "nnei", "x", "X", "p", "q"];
%opts.SelectedVariableNames = ["gene", "expr", "reptime", "hic", "N_nonsilent", "N_silent", "N_noncoding", "n_nonsilent", "n_silent", "n_noncoding", "nnei", "x", "X", "p", "q"];
opts.SelectedVariableNames = ["gene", "p"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
mutsigcv = readtable("C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx", opts, "UseExcel", false);
 