function oncodriveclust = importOncodriveclust
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx
%    Worksheet: OncodriveCLUST
%
% Auto-generated by MATLAB on 16-Oct-2019 12:38:50

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = "OncodriveCLUST";
opts.DataRange = "A2:I16267";

% Specify column names and types
opts.VariableNames = ["GENE", "GENE_LEN", "GENE_NUM_MUTS", "MUTS_IN_CLUST", "NUM_CLUSTERS", "GENE_SCORE", "ZSCORE", "PVALUE", "QVALUE"];
%opts.SelectedVariableNames = ["GENE", "GENE_LEN", "GENE_NUM_MUTS", "MUTS_IN_CLUST", "NUM_CLUSTERS", "GENE_SCORE", "ZSCORE", "PVALUE", "QVALUE"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.SelectedVariableNames = ["GENE", "GENE_SCORE"];

opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
oncodriveclust = readtable("C:\SY\Research+MATLAB\Project 2018\Cancer_Driver_Genes\Data and ML\Synthetic Data\04A_Machine Learning\0_Other_Methods\2020_summary.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts