
 save ColonDriversNamesPredicted.mat colonOG colonTSG colonOGintersect...
     colonTSGintersect colonDriverintersect colonDriver

 save MelanomaDriversNamesPredicted.mat  melanomaOG melanomaTSG ... 
     melanomaOGintersect melanomaTSGintersect melanomaDriverintersect ...
     melanomaDriver

 save PancreaDriversNamesPredicted.mat  pancreaOG pancreaTSG ... 
     pancreaOGintersect pancreaTSGintersect pancreaDriverintersect ...
     pancreaDriver

 save BreastDriversNamesPredicted.mat breastOG breastTSG breastOGintersect...
     breastTSGintersect breastDriverintersect breastDriver
