function ConfMat = ConfusionPlot (C)
% ConfusionPlot returns a graphical representation of the confusion matrix
% given by input "C", generated by a ML model training function 

%% ConfusionPlot
labels = {'Passenger', 'OG', 'TSG'};


numlabels = size(C, 1); % number of labels

% calculate the percentage accuracies
confpercent = 100*C./repmat(sum(C, 2),1,numlabels);

% plotting the colors
figure();
imagesc(confpercent);
title('Confusion Matrix');
xlabel('Output Class'); ylabel('Target Class');

% set the colormap
colormap(flipud(gray));

% Create strings from the matrix values and remove spaces
textStrings = num2str([confpercent(:), C(:)], '%.1f%%\n%d\n');
textStrings = strtrim(cellstr(textStrings));

% Create x and y coordinates for the strings and plot them
[x,y] = meshgrid(1:numlabels);
hStrings = text(x(:),y(:),textStrings(:), ...
    'HorizontalAlignment','center');

% Get the middle value of the color range
midValue = mean(get(gca,'CLim'));

% Choose white or black for the text color of the strings so
% they can be easily seen over the background color
textColors = repmat(confpercent(:) > midValue,1,3);
set(hStrings,{'Color'},num2cell(textColors,2));

% Setting the axis labels
set(gca,'XTick',1:numlabels,...
    'XTickLabel',labels,...
    'YTick',1:numlabels,...
    'YTickLabel',labels,...
    'TickLength',[0 0]);